// Generated by CoffeeScript 1.10.0
(function() {
  var Effects, Entity, Requirements, root;

  Entity = (function() {
    function Entity() {
      this.attributes = {};
    }

    return Entity;

  })();

  Effects = (function() {
    function Effects(story) {
      this.story = story;
    }

    Effects.prototype.setPartyFlags = function(flags, entity) {
      return Core.setFlags(flags, this.story.partyFlags);
    };

    Effects.prototype.setFlags = function(flats, entity) {
      return Core.setFlags(flags, entity.flags);
    };

    Effects.prototype.addEntity = function(count) {
      var i, j, ref, results;
      results = [];
      for (i = j = 0, ref = count; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        results.push(this.story.addEntity());
      }
      return results;
    };

    return Effects;

  })();

  Requirements = (function() {
    function Requirements(story) {
      this.story = story;
    }

    Requirements.prototype.reqPartyFlags = function(flags) {
      return Core.checkFlags(flags, this.story.partyFlags);
    };

    Requirements.prototype.reqFlags = function(flags, entity) {
      return Core.checkFlags(flags, entity.flags);
    };

    return Requirements;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Requirements = Requirements;

  root.Effects = Effects;

  root.Entity = Entity;

}).call(this);
