// Generated by CoffeeScript 1.6.2
(function() {
  var Parser, root;

  Parser = (function() {
    function Parser() {
      this.events = [];
    }

    Parser.newEvent = function() {
      return {
        events: [],
        actions: []
      };
    };

    Parser.parse = function(lines) {
      var line, state, _i, _len;

      state = {
        indent: 0,
        events: []
      };
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        this.parseLine(line, state);
      }
      return state.events;
    };

    Parser.parseLine = function(line, state) {
      var evt, peek, rest, spaces, _ref;

      _ref = Parser.extract(line), spaces = _ref[0], line = _ref[1];
      if (line.length === 0) {
        return;
      }
      peek = line[0];
      rest = line.slice(1).trim();
      if (spaces < state.indent) {
        state.stack.pop();
      }
      if (spaces === 0) {
        evt = Parser.newEvent();
        evt.id = line;
        state.stack = [
          {
            spaces: 0,
            evt: evt
          }
        ];
        state.events.push(evt);
      } else if (peek === '-') {
        this.parseRef(rest, spaces, 'events', state);
      } else if (peek === '?') {
        this.parseRef(rest, spaces, 'actions', state);
      } else {
        evt = state.stack.last().evt;
        evt.text = line;
        if (evt.actionText == null) {
          evt.actionText = line;
        }
      }
      return state.indent = spaces;
    };

    Parser.parseRef = function(line, spaces, collection, state) {
      var evt;

      if (spaces === state.stack.last().spaces) {
        state.stack.pop();
      }
      if (line[0] === '>') {
        evt = line.slice(1).trim();
        return state.stack.last().evt[collection].push(evt);
      } else {
        evt = Parser.newEvent();
        state.stack.last().evt[collection].push(evt);
        state.stack.push({
          spaces: spaces,
          evt: evt
        });
        return evt.actionText = evt.text = line;
      }
    };

    Parser.extract = function(line) {
      var spaces;

      spaces = 0;
      line = line.replace('\t', '  ');
      while (line[0] === ' ') {
        spaces += 1;
        line = line.slice(1);
      }
      return [spaces, line.trim()];
    };

    return Parser;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Parser = Parser;

}).call(this);
