// Generated by CoffeeScript 1.6.2
(function() {
  var Story,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Story = (function() {
    function Story() {
      this.doEntityEffects = __bind(this.doEntityEffects, this);      this.reqs = new Requirements(this);
      this.effs = new Effects(this);
      $('#game').hide();
    }

    Story.prototype.startGame = function() {
      var code, e;

      this.partyFlags = {};
      this.entities = [];
      this.eventCounts = {};
      $('#firepad-container').hide();
      $('#help').hide();
      $('#gameText').empty();
      $('#game').show();
      try {
        code = window.firepad.getText().split('\n');
        config.events = Parser.parse(code);
        return this.showEvent(config.events[0]);
      } catch (_error) {
        e = _error;
        alert(e.message);
        return false;
      }
    };

    Story.prototype.editGame = function() {
      $('#game').hide();
      $('#help').show();
      return $('#firepad-container').show();
    };

    Story.prototype.addEntity = function() {
      var newEntity;

      newEntity = new Entity();
      this.entities.push(newEntity);
      return newEntity;
    };

    Story.prototype.showEvent = function(eventId) {
      var action, actionIdx, _base, _i, _len, _ref, _ref1;

      $('#gameText .action').remove();
      $('#gameImage').hide();
      $('#gameText p').addClass('old');
      this.actions = [];
      if (Object.isString(eventId)) {
        if ((_ref = (_base = this.eventCounts)[eventId]) == null) {
          _base[eventId] = 0;
        }
        this.eventCounts[eventId] += 1;
      }
      this.doEvent(Proto.getEvent(eventId));
      _ref1 = this.actions;
      for (actionIdx = _i = 0, _len = _ref1.length; _i < _len; actionIdx = ++_i) {
        action = _ref1[actionIdx];
        $('#gameText').append("        <p class='action'>          <a onClick=\"doAction('" + actionIdx + "'); return false;\" href=''>            " + action.actionText + "          </a>        </p>");
      }
      if (this.actions.length === 0) {
        return $('#gameText').append("<p><a class=start href='' onClick='startGame(); return false;'>New Game</a></p>");
      }
    };

    Story.prototype.doAction = function(actionIdx) {
      var action;

      action = this.actions[actionIdx];
      return this.showEvent(action);
    };

    Story.prototype.hasRequirements = function(event, entity) {
      var cmd, _i, _len, _ref, _ref1;

      Core.assert(Object.isObject(event));
      _ref = event.commands;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cmd = _ref[_i];
        if (cmd.op.startsWith('req')) {
          Core.assert(this.reqs[cmd.op] != null, "Unknown requirement " + cmd.op);
          if (!this.reqs[cmd.op](cmd.arg, entity)) {
            console.warn("failed requirement " + cmd.op + " for event " + ((_ref1 = event.id) != null ? _ref1 : 'inline'));
            return false;
          }
        }
      }
      if (!this.doEntityEffects(event.effects, true)) {
        return false;
      }
      return true;
    };

    Story.prototype.expandEvent = function(def) {
      if (def.ref != null) {
        return Proto.getEvent(def.ref);
      } else if (Object.isObject(def)) {
        return def;
      } else {
        return Proto.getEvent(def);
      }
    };

    Story.prototype.randEvent = function(eventSet, ctx) {
      var eventSlots, group, prio, randEvt, _ref,
        _this = this;

      _ref = Core.arrify(eventSet).groupBy(function(e) {
        var _ref;

        return (_ref = e.prio) != null ? _ref : 100;
      });
      for (prio in _ref) {
        group = _ref[prio];
        eventSlots = Core.arrify(group).map(function(e) {
          var evt, _ref1;

          evt = _this.expandEvent(e);
          return {
            evt: evt,
            canDo: _this.hasRequirements(evt),
            slots: (_ref1 = e.slots) != null ? _ref1 : 1
          };
        });
        eventSlots.remove(function(def) {
          return !def.canDo;
        });
        if (!eventSlots.isEmpty()) {
          break;
        }
      }
      if (eventSlots != null) {
        randEvt = this.randEntry(eventSlots);
        if (randEvt != null) {
          return randEvt.evt;
        }
      }
      return null;
    };

    Story.prototype.randEntry = function(slotDefs, ctx) {
      var entry, targetChance, totalSlots, _i, _len, _ref;

      if (ctx == null) {
        ctx = {};
      }
      totalSlots = slotDefs.sum(function(e) {
        var _ref;

        return (_ref = e.slots) != null ? _ref : 1;
      });
      targetChance = Math.random() * totalSlots;
      for (_i = 0, _len = slotDefs.length; _i < _len; _i++) {
        entry = slotDefs[_i];
        targetChance -= (_ref = entry.slots) != null ? _ref : 1;
        if (targetChance <= 0 || totalSlots === 0) {
          return entry;
        }
      }
      return null;
    };

    Story.prototype.doCommands = function(entry) {
      var cmd, _i, _len, _ref;

      _ref = entry.commands;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cmd = _ref[_i];
        if (this.effs[cmd.op] != null) {
          this.effs[cmd.op](cmd.arg);
        }
      }
    };

    Story.prototype.addText = function(txt, entity) {
      var klass;

      klass = entity != null ? 'special' : '';
      if (txt != null) {
        txt = TextHelper.parse(txt);
        if (entity != null) {
          txt = TextHelper.replaceAtts(txt, entity.attributes);
        }
        return $('#gameText').append("<p class=" + klass + ">" + txt + "</p>");
      }
    };

    Story.prototype.doEvent = function(event, entity) {
      var action, actionId, nextEventRef, _i, _len, _ref;

      Core.assert(Object.isObject(event));
      if (event.id != null) {
        console.log("do event [" + event.id + "]");
      }
      this.addText(event.text, entity);
      this.doCommands(event);
      this.doEntityEffects(event.effects);
      _ref = Core.arrify(event.actions);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        actionId = _ref[_i];
        action = Proto.getEvent(actionId);
        if (this.hasRequirements(action)) {
          this.actions.push(action);
        }
      }
      nextEventRef = this.randEvent(event.events);
      if (nextEventRef != null) {
        return this.doEvent(nextEventRef);
      }
    };

    Story.prototype.doEntityEffects = function(effects, testOnly) {
      var allEntities, consumedEntities, count, eff, ent, entities, evt, failed, maxCount, minCount, optional, _i, _j, _len, _len1, _ref, _ref1, _ref2, _ref3, _ref4,
        _this = this;

      if (testOnly == null) {
        testOnly = false;
      }
      if (effects == null) {
        return true;
      }
      consumedEntities = [];
      _ref = Core.arrify(effects);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        eff = _ref[_i];
        optional = (_ref1 = eff.optional) != null ? _ref1 : true;
        if (optional && testOnly) {
          continue;
        }
        evt = this.expandEvent(eff);
        allEntities = this.entities;
        entities = allEntities.filter(function(ent) {
          if (__indexOf.call(consumedEntities, ent) >= 0) {
            return false;
          }
          return _this.hasRequirements(evt, ent);
        });
        count = (_ref2 = evt.count) != null ? _ref2 : 1;
        failed = false;
        if (count === 'all') {
          if (entities.length < allEntities.length) {
            if (optional) {
              continue;
            } else {
              return false;
            }
          }
        } else if (count === 'any') {

        } else {
          _ref3 = Core.parseRange(count), minCount = _ref3[0], maxCount = _ref3[1];
          if (entities.length < minCount) {
            if (optional) {
              continue;
            } else {
              return false;
            }
          }
          entities = entities.sample(maxCount);
        }
        if (entities.isEmpty()) {
          if (optional) {
            continue;
          } else {
            return false;
          }
        }
        if (!testOnly) {
          if ((evt.chance != null) && Math.random() > evt.chance) {
            continue;
          }
          _ref4 = entities.randomize();
          for (_j = 0, _len1 = _ref4.length; _j < _len1; _j++) {
            ent = _ref4[_j];
            this.doEvent(evt, ent);
            if (eff.consume) {
              consumedPersons.push(ch);
            }
          }
        }
      }
      return true;
    };

    return Story;

  })();

  if (typeof window !== "undefined" && window !== null) {
    window.doAction = function(actionIdx) {
      window.story.doAction(actionIdx);
      return false;
    };
    window.startGame = function() {
      return window.story.startGame();
    };
    window.editGame = function() {
      return window.story.editGame();
    };
    window.help = function() {
      return window.story.showHelp();
    };
    window.onload = function() {
      return window.story = new Story;
    };
  }

}).call(this);
